server:
  port: 8082

spring:
  application:
    name: user-server

  datasource:
    url: jdbc:postgresql://localhost:5433/antcamp
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true