server:
  port: 8082

spring:
  application:
    name: user-server

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true