spring:
  application:
    name: competition-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8092

# [추가] 토픽명 매핑 (CompetitionTopicProperties와 연결)
topics:
  competition:
    started: competition.started
    finished: competition.finished
