global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - alert-rules.yaml

scrape_configs:
  - job_name: 'antcamp-eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - eureka-server:8761

  - job_name: 'antcamp-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - gateway-service:8080

  - job_name: 'antcamp-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - user-service:8082

  - job_name: 'antcamp-trade'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - trade-service:8084

  - job_name: 'antcamp-asset'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - asset-service:8086

  - job_name: 'antcamp-competition'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - competition-service:8092

  - job_name: 'antcamp-ranking'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - ranking-service:8094

  - job_name: 'antcamp-assistant'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - assistant-service:8096

  - job_name: 'antcamp-notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - notification-service:8098