server:
  port: 8086

spring:
  application:
    name: asset-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: asset-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "io.antcamp.assetservice.domain.event.payload"

  data:
    redis:
      host: localhost
      port: ${SPRING_DATA_REDIS_PORT:6379}

topics:
  competition:
    started: competition.started
    finished: competition.finished
    ticked: competition.ticked
  asset:
    total-calculated: asset.total-calculated